device: mps
test_csv_path:
- data/TKR/splits/original_v0_seed_40_fold_0/test.csv
val_csv_path:
- data/TKR/splits/original_v0_seed_40_fold_0/val.csv
- data/TKR/splits/original_v0_seed_40_fold_1/val.csv
- data/TKR/splits/original_v0_seed_40_fold_2/val.csv
- data/TKR/splits/original_v0_seed_40_fold_3/val.csv
- data/TKR/splits/original_v0_seed_40_fold_4/val.csv
result_dir:
- results/inference/fold0
multimodal_model_dir: inference_asset/fold0/models/multimodal
image_only_model_dir: null
yolo_model_path: inference_asset/fold0/yolo/v1.pt
tabular_processor_dir: inference_asset/fold0/processors
multimodal_model:
  name: DINOv2FusionClassifier
  type: multimodal
  params:
    backbone_name: facebook/dinov2-small
    num_classes: 2
    tabular_dim: 3
    tabular_hidden_dim: 32
    mlp_dim: 256
    use_lora: true
    lora_cfg:
      r: 64
      alpha: 128
      dropout: 0.1
      target_modules:
      - query
      - key
      - value
      - dense
image_only_model:
  name: DINOv2Classifier
  type: image_only
  params:
    backbone_name: facebook/dinov2-small
    num_classes: 2
    use_mlp: true
    mlp_dim: 256
    use_lora: true
    lora_cfg:
      r: 64
      alpha: 128
      dropout: 0.1
      target_modules:
      - query
      - key
      - value
      - dense
image_transforms:
  image_size:
  - 224
  - 224
  padding_mode: constant
calibrate_parameters:
  multimodal:
    temperatures:
    - 3.4134
    - 1.073
    - 6.5557
    - 2.3276
    - 2.2738
    threshold: 0.5
  image_only:
    temperatures: null
    threshold: null
analyze_model:
  path: inference_asset/models/multimodal/run1_split_versionseed_40_fold_0_stage2_finetune_best_model.pth
  name: DINOv2FusionClassifier
  type: multimodal
  params:
    backbone_name: facebook/dinov2-small
    num_classes: 2
    tabular_dim: 3
    tabular_hidden_dim: 32
    mlp_dim: 256
    use_lora: true
    lora_cfg:
      r: 64
      alpha: 128
      dropout: 0.1
      target_modules:
      - query
      - key
      - value
      - dense
reliability_diagram_filename: reliability_diagram.png
auc_pr_filename             : auc_pr.png
auc_roc_filename            : auc_roc.png
tsne_filename               : tsne.png
tsne_perplexities:
- 5
- 15
- 30
- 35