# yolo_module/cropper.py
import os
import json
import cv2
import torch
import shutil
import numpy as np
from ultralytics import YOLO
from tqdm import tqdm

EXPAND_RATIO = None
MASK_ONLY = True

class WoundCropper:
    def __init__(self, model_path: str, output_dir: str | None = None, conf_thres=0.25, expand_ratio=None, mask_only=False):
        self.model = YOLO(model_path)
        self.output_dir = output_dir
        self.conf_thres = conf_thres
        self.expand_ratio = expand_ratio
        self.mask_only = mask_only

    def run(self, source_map_path: str, target_map_path: str):
        """
        Args:
            source_map_path: image_id_map.json (generated by builder)
            target_map_path: output image_id_map_cropped.json
        """
        if self.output_dir is None:
            print("[Cropper]\t [Warning]\t output directory is None.")
        else:
            self._create_output_dir(self.output_dir)

        with open(source_map_path, "r", encoding="utf-8") as f:
            source_map = json.load(f)
            
        print(f"Loaded {len(source_map)} images from {source_map_path}")
        
        new_map = {}
        
        for img_id, img_path in tqdm(source_map.items(), desc="Cropping Wounds"):
            if not os.path.exists(img_path):
                continue

            try:
                cropped_img = self._crop_single_image(img_path, self.expand_ratio)
                
                if cropped_img is not None and self.output_dir is not None:
                    fname = os.path.basename(img_path)
                    save_path = os.path.join(self.output_dir, fname)
                    
                    cv2.imwrite(save_path, cropped_img)
                    
                    new_map[img_id] = save_path
                else:
                    print("[Cropper]\t [Warning]\t Failed to return cropped image or no output directory.")
                    
            except Exception as e:
                print(f"Error processing {img_id}: {e}")

        with open(target_map_path, "w", encoding="utf-8") as f:
            json.dump(new_map, f, indent=4, ensure_ascii=False)
            
        print(f"Cropped map saved to: {target_map_path}")

    def _create_output_dir(self, output_dir: str):
        if os.path.exists(output_dir):
            print(f"Removing old output directory: {self.output_dir}")
            shutil.rmtree(output_dir)
        
        os.makedirs(output_dir, exist_ok=True)

    def _crop_single_image(self, img_path: str, expand_ratio: float | None = None):
        img = cv2.imread(img_path)

        if img is None:
            print(f"[Cropper]\t [Error]\t while loading {img_path}...")
            return None

        results = self.model.predict(img, conf=self.conf_thres, verbose=False)
        
        if not results or (results[0].boxes is not None and len(results[0].boxes)) == 0:
            return None
            
        boxes = results[0].boxes
        if boxes is None: raise ValueError(f"[Cropper]\t [Error]\t No bboxes detected.")

        best_box_idx = torch.argmax(torch.Tensor(boxes.conf))
        x1, y1, x2, y2 = boxes.xyxy[best_box_idx].cpu().numpy().astype(int)
                
        h, w = img.shape[:2]
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(w, x2), min(h, y2)
        
        if expand_ratio is not None:
            x1, y1, x2, y2 = self._expand_bbox(x1, y1, x2, y2, w, h, expand_ratio)
        
        # Compute cropped image
        crop_img = img[y1:y2, x1:x2]

        # Compute masked image
        mask = np.zeros((h, w), dtype=np.uint8)
        cv2.rectangle(mask, (x1, y1), (x2, y2), 255, -1)
        mask_img = img.copy()
        mask_img[mask == 0] = 255

        return mask_img if self.mask_only else crop_img
                
    def _expand_bbox(self, x1, y1, x2, y2, width, height, expand_ratio):
        crop_w = x2 - x1
        crop_h = y2 - y1
        pad_x = int(crop_w * expand_ratio)
        pad_y = int(crop_h * expand_ratio)

        new_x1 = max(0, x1 - pad_x)
        new_y1 = max(0, y1 - pad_y)
        new_x2 = min(width, x2 + pad_x)
        new_y2 = min(height, y2 + pad_y)

        return new_x1, new_y1, new_x2, new_y2


if __name__ == "__main__":
    MODEL_PATH = "yolo/models/v1.pt"
    OUTPUT_DIR = f"data/TKR/processed/cropped_images_expand_{EXPAND_RATIO}_maskonly_{MASK_ONLY}"
    IMG_MAP_FILE = "data/TKR/processed/image_id_map.json"
    OUTPUT_MAP_FILE = f"data/TKR/processed/cropped_image_id_map{EXPAND_RATIO}_{MASK_ONLY}.json"

    cropper = WoundCropper(MODEL_PATH, OUTPUT_DIR, expand_ratio=EXPAND_RATIO, mask_only=MASK_ONLY)
    cropper.run(IMG_MAP_FILE, OUTPUT_MAP_FILE)